services:
  rtsp-server:
    container_name: rtspserver
    image: bluenviron/mediamtx:latest
    ports:
      - "8554:8554/tcp"
      - "8554:8554/udp"
      - "8888:8888"   # HLS
    restart: unless-stopped

  streamer:
    container_name: streamer
    build: .
    depends_on:
      - rtsp-server
    volumes:
      - ./videos:/videos